//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkDesktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InkDesktop.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm stopping webserver?.
        /// </summary>
        internal static string CFM_STOP {
            get {
                return ResourceManager.GetString("CFM_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating image.
        /// </summary>
        internal static string ERROR_GEN_IMAGE {
            get {
                return ResourceManager.GetString("ERROR_GEN_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting signature from InkHub.
        /// </summary>
        internal static string ERROR_INK_HUB_SIGN {
            get {
                return ResourceManager.GetString("ERROR_INK_HUB_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialised logging action.
        /// </summary>
        internal static string INIT_LOG_FAIL {
            get {
                return ResourceManager.GetString("INIT_LOG_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ink Desktop.
        /// </summary>
        internal static string INK_DESKTOP {
            get {
                return ResourceManager.GetString("INK_DESKTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Port Number.
        /// </summary>
        internal static string INVALID_PORT {
            get {
                return ResourceManager.GetString("INVALID_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signature present.
        /// </summary>
        internal static string NO_SIGNATURE_PRESENT {
            get {
                return ResourceManager.GetString("NO_SIGNATURE_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connected pen device.
        /// </summary>
        internal static string NOT_CONNECTED {
            get {
                return ResourceManager.GetString("NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception listening to port.
        /// </summary>
        internal static string PORT_LISTEN_EXCEPTION {
            get {
                return ResourceManager.GetString("PORT_LISTEN_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server still pending user response from previous request.
        /// </summary>
        internal static string SERVER_BUSY_PREV_REQ {
            get {
                return ResourceManager.GetString("SERVER_BUSY_PREV_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to show SignatureCapture, please restart application.
        /// </summary>
        internal static string SIGN_CAPT_UNABLE_SHOW {
            get {
                return ResourceManager.GetString("SIGN_CAPT_UNABLE_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InkDesktop is still running in the background.
        /// </summary>
        internal static string TOOL_TIP_MSG_NOT_CLOSED {
            get {
                return ResourceManager.GetString("TOOL_TIP_MSG_NOT_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebManager.
        /// </summary>
        internal static string WEB_MANAGER {
            get {
                return ResourceManager.GetString("WEB_MANAGER", resourceCulture);
            }
        }
    }
}
